// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api-keys/": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "get all API keys by some filters{id,name,limit,beforeId,afterId}",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "ApiKey"
                ],
                "summary": "Get all API keys",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Filter by id",
                        "name": "id",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Filter by key",
                        "name": "key",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Filter by beforeId",
                        "name": "beforeId",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Filter by afterId",
                        "name": "afterId",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Number of items per page (default 10)",
                        "name": "limit",
                        "in": "query"
                    }
                ],
                "responses": {}
            }
        },
        "/api-keys/new": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Create a new API key for a user",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "ApiKey"
                ],
                "summary": "Create a new API key",
                "parameters": [
                    {
                        "description": "API Key payload",
                        "name": "apiKey",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dtos.CreateApiKeyDTO"
                        }
                    }
                ],
                "responses": {}
            }
        },
        "/api-keys/{key}": {
            "put": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Update API key for a user",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "ApiKey"
                ],
                "summary": "Update API key",
                "parameters": [
                    {
                        "type": "string",
                        "description": "API key",
                        "name": "key",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "API Key payload",
                        "name": "apiKey",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dtos.UpdateApiKeyDTO"
                        }
                    }
                ],
                "responses": {}
            }
        },
        "/auth/login": {
            "post": {
                "description": "login to user account",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Auth"
                ],
                "summary": "Login to hello-bangla-tts",
                "parameters": [
                    {
                        "description": "user login dto",
                        "name": "login",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dtos.LoginDTO"
                        }
                    }
                ],
                "responses": {}
            }
        },
        "/auth/logout": {
            "post": {
                "description": "logout from user account",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Auth"
                ],
                "summary": "logout from hello-bangla-tts",
                "responses": {}
            }
        },
        "/auth/refresh": {
            "post": {
                "description": "refresh users access token",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Auth"
                ],
                "summary": "Refresh token",
                "parameters": [
                    {
                        "description": "user login dto",
                        "name": "login",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dtos.RefreshTokenDTO"
                        }
                    }
                ],
                "responses": {}
            }
        },
        "/auth/register": {
            "post": {
                "description": "create a new user account in sender-bee",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Auth"
                ],
                "summary": "Register new user",
                "parameters": [
                    {
                        "description": "user register dto",
                        "name": "register",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dtos.RegisterDTO"
                        }
                    }
                ],
                "responses": {}
            }
        },
        "/support/ticket": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Retrieve tickets filtered by business_id and other optional filters",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Ticket"
                ],
                "summary": "Get tickets",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Business ID",
                        "name": "business_id",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Serial",
                        "name": "serial",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "limit",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "beforeId",
                        "name": "beforeId",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "afterId",
                        "name": "afterId",
                        "in": "query"
                    }
                ],
                "responses": {}
            }
        },
        "/support/ticket/new": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Create a ticket for a support",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Ticket"
                ],
                "summary": "Create Tickets",
                "parameters": [
                    {
                        "description": "ticket payload",
                        "name": "ticket",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dtos.CreateTicketDTO"
                        }
                    }
                ],
                "responses": {}
            }
        },
        "/support/ticket/{id}": {
            "put": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Update ticket fields by ID",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Ticket"
                ],
                "summary": "Update ticket",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Ticket ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "ticket payload",
                        "name": "ticket",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dtos.UpdateTicketDTO"
                        }
                    }
                ],
                "responses": {}
            },
            "delete": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Delete ticket by ID",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Ticket"
                ],
                "summary": "Delete ticket",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Ticket ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {}
            }
        },
        "/user/": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "get all hello-bangla-tts users profile by some filters{id,name,limit,beforeId,afterId}",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "User"
                ],
                "summary": "Get all hello-bangla-tts users",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Filter by id",
                        "name": "id",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Filter by name",
                        "name": "name",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Filter by beforeId",
                        "name": "beforeId",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Filter by afterId",
                        "name": "afterId",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Number of items per page (default 10)",
                        "name": "limit",
                        "in": "query"
                    }
                ],
                "responses": {}
            }
        },
        "/user/profile": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "get a hello-bangla-tts users profile by id",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "User"
                ],
                "summary": "Get Profile by id",
                "responses": {}
            }
        }
    },
    "definitions": {
        "dtos.CreateApiKeyDTO": {
            "type": "object",
            "properties": {
                "name": {
                    "type": "string"
                }
            }
        },
        "dtos.CreateTicketDTO": {
            "type": "object",
            "properties": {
                "business_id": {
                    "type": "string"
                },
                "category": {
                    "type": "string"
                },
                "priority": {
                    "$ref": "#/definitions/models.TicketPriority"
                },
                "status": {
                    "$ref": "#/definitions/models.TicketStatus"
                },
                "subject": {
                    "type": "string"
                }
            }
        },
        "dtos.LoginDTO": {
            "type": "object",
            "properties": {
                "email": {
                    "type": "string"
                },
                "password": {
                    "type": "string"
                }
            }
        },
        "dtos.RefreshTokenDTO": {
            "type": "object",
            "properties": {
                "refresh_token": {
                    "type": "string"
                }
            }
        },
        "dtos.RegisterDTO": {
            "type": "object",
            "properties": {
                "email": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "password": {
                    "type": "string"
                }
            }
        },
        "dtos.UpdateApiKeyDTO": {
            "type": "object",
            "properties": {
                "is_active": {
                    "type": "boolean"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "dtos.UpdateTicketDTO": {
            "type": "object",
            "properties": {
                "category": {
                    "type": "string"
                },
                "priority": {
                    "$ref": "#/definitions/models.TicketPriority"
                },
                "status": {
                    "$ref": "#/definitions/models.TicketStatus"
                },
                "subject": {
                    "type": "string"
                }
            }
        },
        "models.TicketPriority": {
            "type": "string",
            "enum": [
                "high",
                "medium",
                "low"
            ],
            "x-enum-varnames": [
                "TicketPriorityHigh",
                "TicketPriorityMedium",
                "TicketPriorityLow"
            ]
        },
        "models.TicketStatus": {
            "type": "string",
            "enum": [
                "open",
                "pending",
                "close"
            ],
            "x-enum-varnames": [
                "TicketStatusOpen",
                "TicketStatusPending",
                "TicketStatusClose"
            ]
        }
    },
    "securityDefinitions": {
        "BearerAuth": {
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:5001",
	BasePath:         "/api/v1",
	Schemes:          []string{"http", "https"},
	Title:            "HelloBanglaTTS-Backend-APIs",
	Description:      "Hello Bangla TTS is a Bangla language based Ai platform writen in go.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
